version: 2.1

# Orbs for additional functionality
orbs:
  node: circleci/node@5.2.0
  gcp-cli: circleci/gcp-cli@3.1.0

# Executors define the environment
executors:
  node-executor:
    docker:
      - image: cimg/node:20.18.2
    working_directory: ~/repo

# Reusable commands
commands:
  install-dependencies:
    description: "Install dependencies with caching"
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          paths:
            - node_modules
            - packages/*/node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

  detect-changes:
    description: "Detect which packages have changed"
    parameters:
      package:
        type: string
    steps:
      - run:
          name: Check if << parameters.package >> changed
          command: |
            # Get changed files
            if [ -z "$CIRCLE_COMPARE_URL" ]; then
              # First commit or no previous commit - run all tests
              echo "No previous commit to compare. Running tests."
              echo "true" > /tmp/<< parameters.package >>_changed
            else
              # Extract commit range from compare URL
              COMMIT_RANGE=$(echo $CIRCLE_COMPARE_URL | sed 's:^.*/compare/::g')

              # Check if package files changed
              if git diff --name-only $COMMIT_RANGE | grep -q "^packages/<< parameters.package >>/"; then
                echo "<< parameters.package >> has changes. Running tests."
                echo "true" > /tmp/<< parameters.package >>_changed
              else
                echo "<< parameters.package >> has no changes. Skipping."
                echo "false" > /tmp/<< parameters.package >>_changed
              fi
            fi

# Jobs
jobs:
  setup:
    executor: node-executor
    steps:
      - checkout
      - install-dependencies
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

  test-core:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/repo
      - detect-changes:
          package: core
      - run:
          name: Run Core Tests
          command: |
            if [ "$(cat /tmp/core_changed)" = "true" ] || [ "$CIRCLE_BRANCH" = "main" ]; then
              npm run test:core
            else
              echo "Skipping core tests - no changes detected"
            fi
      - store_test_results:
          path: packages/core/coverage
      - store_artifacts:
          path: packages/core/coverage

  test-web:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/repo
      - detect-changes:
          package: web
      - run:
          name: Run Web Tests
          command: |
            if [ "$(cat /tmp/web_changed)" = "true" ] || [ "$CIRCLE_BRANCH" = "main" ]; then
              npm run test --workspace=web
            else
              echo "Skipping web tests - no changes detected"
            fi

  test-cli:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/repo
      - detect-changes:
          package: cli
      - run:
          name: Run CLI Tests
          command: |
            if [ "$(cat /tmp/cli_changed)" = "true" ] || [ "$CIRCLE_BRANCH" = "main" ]; then
              npm run test --workspace=cli
            else
              echo "Skipping cli tests - no changes detected"
            fi

  test-client:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/repo
      - detect-changes:
          package: client
      - run:
          name: Run Client Tests
          command: |
            if [ "$(cat /tmp/client_changed)" = "true" ] || [ "$CIRCLE_BRANCH" = "main" ]; then
              npm run test --workspace=client
            else
              echo "Skipping client tests - no changes detected"
            fi

  build-core:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/repo
      - detect-changes:
          package: core
      - run:
          name: Build Core
          command: |
            if [ "$(cat /tmp/core_changed)" = "true" ] || [ "$CIRCLE_BRANCH" = "main" ]; then
              npm run build --workspace=core
            else
              echo "Skipping core build - no changes detected"
            fi
      - persist_to_workspace:
          root: ~/repo
          paths:
            - packages/core/dist

  build-web:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/repo
      - detect-changes:
          package: web
      - run:
          name: Build Web
          command: |
            if [ "$(cat /tmp/web_changed)" = "true" ] || [ "$CIRCLE_BRANCH" = "main" ]; then
              npm run build --workspace=web
            else
              echo "Skipping web build - no changes detected"
            fi

  build-cli:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/repo
      - detect-changes:
          package: cli
      - run:
          name: Build CLI
          command: |
            if [ "$(cat /tmp/cli_changed)" = "true" ] || [ "$CIRCLE_BRANCH" = "main" ]; then
              npm run build --workspace=cli
            else
              echo "Skipping cli build - no changes detected"
            fi

  build-client:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/repo
      - detect-changes:
          package: client
      - run:
          name: Build Client
          command: |
            if [ "$(cat /tmp/client_changed)" = "true" ] || [ "$CIRCLE_BRANCH" = "main" ]; then
              npm run build --workspace=client
            else
              echo "Skipping client build - no changes detected"
            fi
      - persist_to_workspace:
          root: ~/repo
          paths:
            - packages/client/dist

  deploy-web-api:
    docker:
      - image: cimg/base:stable
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - setup_remote_docker:
          docker_layer_caching: true
      - gcp-cli/install
      - run:
          name: Authenticate with GCP
          command: |
            # Decode the base64-encoded service account key
            echo "$GCP_SERVICE_ACCOUNT_KEY" | base64 -d > ${HOME}/gcp-key.json
            gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
            gcloud config set project $GCP_PROJECT_ID
      - run:
          name: Configure Docker for GCP
          command: |
            gcloud auth configure-docker
      - run:
          name: Build and Push Docker Image
          command: |
            # Build from root to include both core and web packages
            cd ~/repo
            IMAGE_NAME="gcr.io/${GCP_PROJECT_ID}/${CLOUD_RUN_SERVICE_NAME_WEB}:${CIRCLE_SHA1}"
            docker build -f packages/web/Dockerfile -t $IMAGE_NAME .
            docker push $IMAGE_NAME

            # Also tag as latest
            docker tag $IMAGE_NAME "gcr.io/${GCP_PROJECT_ID}/${CLOUD_RUN_SERVICE_NAME_WEB}:latest"
            docker push "gcr.io/${GCP_PROJECT_ID}/${CLOUD_RUN_SERVICE_NAME_WEB}:latest"
      - run:
          name: Deploy to Cloud Run
          command: |
            gcloud run deploy ${CLOUD_RUN_SERVICE_NAME_WEB} \
              --image gcr.io/${GCP_PROJECT_ID}/${CLOUD_RUN_SERVICE_NAME_WEB}:${CIRCLE_SHA1} \
              --region ${CLOUD_RUN_REGION} \
              --platform managed \
              --allow-unauthenticated \
              --set-env-vars "NODE_ENV=production,OPENAI_API_KEY=${OPENAI_API_KEY},GITHUB_TOKEN=${GITHUB_TOKEN},CIRCLECI_TOKEN=${CIRCLECI_TOKEN}" \
              --memory 512Mi \
              --cpu 1 \
              --max-instances 10 \
              --timeout 60
      - run:
          name: Get Service URL
          command: |
            SERVICE_URL=$(gcloud run services describe ${CLOUD_RUN_SERVICE_NAME_WEB} \
              --region ${CLOUD_RUN_REGION} \
              --format 'value(status.url)')
            echo "Backend API deployed to: $SERVICE_URL"
            echo $SERVICE_URL > /tmp/backend-url.txt
      - store_artifacts:
          path: /tmp/backend-url.txt

  deploy-client:
    docker:
      - image: cimg/node:20.18.2
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Update Firebase Project Config
          command: |
            # Replace placeholder with actual project ID
            sed -i "s/YOUR_GCP_PROJECT_ID/${GCP_PROJECT_ID}/g" .firebaserc
      - run:
          name: Deploy to Firebase Hosting
          command: |
            npx -y firebase-tools deploy --only hosting --token ${FIREBASE_TOKEN} --non-interactive
      - run:
          name: Get Hosting URL
          command: |
            echo "Frontend deployed to: https://${GCP_PROJECT_ID}.web.app"
            echo "https://${GCP_PROJECT_ID}.web.app" > /tmp/frontend-url.txt
      - store_artifacts:
          path: /tmp/frontend-url.txt

# Workflows
workflows:
  version: 2
  test-build-and-deploy:
    jobs:
      # Setup - runs for all commits
      - setup

      # Test jobs - run in parallel after setup
      - test-core:
          requires:
            - setup
      - test-web:
          requires:
            - setup
      - test-cli:
          requires:
            - setup
      - test-client:
          requires:
            - setup

      # Build jobs - run after tests pass
      - build-core:
          requires:
            - test-core
      - build-web:
          requires:
            - test-web
      - build-cli:
          requires:
            - test-cli
      - build-client:
          requires:
            - test-client

      # Deployment jobs - only on main branch after successful builds
      - deploy-web-api:
          requires:
            - build-core
            - build-web
          filters:
            branches:
              only: main
      - deploy-client:
          requires:
            - build-client
          filters:
            branches:
              only: main
